### ISSUE TITLE
When my material name node name is not in English, it will not be displayed

### ISSUE THREAD

**Issue by chenpaner** [strike-digital/NGviewer#1]
Python: Traceback (most recent call last):
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\NGviewer beta 1_3.py", line 351, in draw
    if bpy.data.materials[ng_tool.material] is not None and bpy.context.active_object.active_material is not None:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 2: invalid continuation byte

Python: Traceback (most recent call last):
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\NGviewer beta 1_3.py", line 421, in draw
    draw_sockets(self,context)
  File "C:\Users\CP\AppData\Roaming\Blender Foundation\Blender\Big addons\addons\NGviewer beta 1_3.py", line 136, in draw_sockets
    group_node = node_tree.nodes[ng_tool.node_group]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 2: invalid continuation byte

Can you help fix it？Have a nice day！

**Comment by chenpaner** [comment]
My blender is 3.6 in win11！！
